### ISSUE TITLE
Contribution Proposal - Postman Virtual Workshop (Sule-balogun Olanrewaju)

### ISSUE THREAD

**Issue by LarrySul** [postman-open-technologies/Postman-Supernova-Program#4]
# Contribution Proposal

The Postman Virtual Workshop seeks to bring together season Software engineering professionals and QA experts to talk about Topics Collections, Git Flows and Postman Flows. It will be a 2 hour season that features 3 speakers with 45mins each hands experience.  It will be a virtual event and strictly by registerations.

Link to planned event can be found [here](https://www.townscript.com/e/postman-virtual-workshop-332440) 

## Contribution Type
- [ ] Event Speaking
- [x] Event Hosting
- [ ] Article / Blog Post
- [ ] Video / Livestream
- [ ] Quickstarts / Translation Assistance

### For event types, will this event be in-person, virtual or hybrid?
- [x] Virtual
- [ ] In-Person
- [ ] Hybrid

### Contribution Name

Sule-balogun Olanrewaju

### Contribution Date
Please enter formatted as 06/17/2023

### Link to Contribution (optional)
Link to your contribution, if applicable

https://www.townscript.com/e/postman-virtual-workshop-332440

### Projected Attendance (optional)
Rough estimates are acceptable ( 100) attendees

# Details
What are your plans for this contribution?

The event is going to be a virtual one so there's not much of planning that will go into it. I'm still not very much settled in the UK to host a physical event. So I'll need attendees to fill a form then ask what they would like to learn in future workshop and also work with invited speakers before the event to do a demo prep on what they will teach and also help the speakers prepare better. Maybe stipend in the futute to send to attendees who participate well or for refreshment purpose for the speakers. Outside of those I look forward to hosting an event for API Enthusiast and Professionals.

**Comment by Kcorb95** [comment]
Hey @LarrySul, this looks great!

I can see on the site that you have the speaker outlines:

```
Guest Speaker 1
Understanding collections,
Working with collection runner
Generating Test data from runners

Guest Speaker 2
Understanding Git workflows in Postman
How to connect Postman to Github Repo
How to collaborate effectively with team mates by using Github to make create Pull & Push Request

Guest Speaker 3
What is Postman Flows
Fork and Send your first flow request
Authorization, Handling response in request, Passing data in flows 
```

I think it would be helpful to have some more info about each speaker such as their name, job title/company if possible and also a bit more about their talks.

For example, here's what we typically get from Postman DevRel events:

>Speaker: Ian Douglas, Postman senior developer advocate
Talk Title: **A Tale of Three APIs: REST, Async, and gRPC Face Off**
Abstract: Let's delve into the world of API types and explore their respective benefits and disadvantages. We will compare and contrast the most common API types, including REST, Async, and gRPC, to see where each excels. Attendees will gain insight into how to choose the right API for their specific needs, considering factors such as performance and ease of integration.

Otherwise I'd love to get some socials for this scheduled :)
I've put together an image that we'll be using to promote, but feel free to utilize when sharing with your network as well.
![thumbnail-supernova-template](https://github.com/postman-open-technologies/Postman-Supernova-Program/assets/40337763/c70dc8f7-b87c-4d8a-bde0-9753ffb99c3c)

Please be sure to share with your network, over socials and on the [Postman community forums](https://community.postman.com/c/events/6). Once the event has concluded, if you could fill out the [contribution report](https://airtable.com/shrM6Uh7WqOEJJQZ7), we'll be able to get it added to our website as well :)

**Comment by LarrySul** [comment]
Hi @Kcorb95, 

Thanks for the tips, really helpful. I have gone ahead to add more speaker details and also created a flier for the event with speaker names and where they also work. 

![new postman](https://github.com/postman-open-technologies/Postman-Supernova-Program/assets/29729601/ace8d202-b10a-4286-8797-1bbbd642b980).

I've also tweeted about the upcoming event via [twitter]( https://twitter.com/bigdevlarry/status/1668169597860683777?s=20) & [postman community ](https://community.postman.com/t/postman-virtual-workshop/48428).

Do let me know if you need anyother info for the promo or event.

**Comment by Kcorb95** [comment]
Thanks Larry! This flier looks much better! :)
